#!/usr/bin/env bash

. $HOME/.xenv.sh

if command -v xss-lock > /dev/null 2>&1; then
    if command -v xsecurelock > /dev/null 2>&1; then
        exec xss-lock xsecurelock
    else
        exec xss-lock xlock
    fi
else
    exit 1
fi

