[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    refreshPeriod = "168h"
{{- if and (not .ephemeral) (not .headless) }}
{{-   $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}/sketchybar-app-font.ttf"]
    type = "file"
    url = "https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.5/sketchybar-app-font.ttf"
    refreshPeriod = "168h"
{{- end -}}