unbind C-b
set-option -g prefix C-a

# Mouse
set-option -g mouse on

# Key binding in the status line (bind-key :)
set-option -g status-keys emacs

# Copy-mode
set-window-option -g mode-keys vi

# form vim/tmux d/y buffer sync
set -g focus-events

# reload ~/.tmux.conf using PREFIX r
bind-key r source-file ~/.tmux.conf \; display-message "Reloaded!"

# Default terminal is 256 colors
set -g default-terminal "xterm-256color"

# Add truecolor support (tmux info | grep Tc)
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Index starts from 1
set-option -g base-index 1
set-option -g pane-base-index 1

# Synchronize panes
bind-key * set-window-option synchronize-pane

# Renumber windows when a window is closed
set-option -g renumber-windows on

set -sg escape-time 0
set -g status-interval 0

# Name windows after the running command
set-window-option -g automatic-rename on
set-window-option -g automatic-rename-format '#{pane_current_command}'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.3.0'

set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_text ' #{pane_current_command}'
set -g @catppuccin_window_current_text ' #{pane_current_command}'
set-option -g @tpm-clean 'P' # key binding to clean TPM plugins
run '~/.tmux/plugins/tpm/tpm'