#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar                   all:40:0       \
                mouse_follows_focus            off            \
                focus_follows_mouse            autofocus      \
                window_zoom_persist            off            \
                window_placement               second_child   \
                window_shadow                  on             \
                window_opacity                 off            \
                window_opacity_duration        0.0            \
                active_window_opacity          1.0            \
                normal_window_opacity          0.8            \
                window_animation_duration      0.0            \
                window_animation_frame_rate    120            \
                window_animation_easing        ease_out_quint \
                insert_feedback_color          0xff9dd274     \
                split_ratio                    0.50           \
                split_type                     auto           \
                auto_balance                   off            \
                layout                         bsp            \
                mouse_modifier                 fn             \
                mouse_action1                  move           \
                mouse_action2                  resize         \
                mouse_drop_action              swap           \
                top_padding                    10             \
                bottom_padding                 10             \
                left_padding                   10             \
                right_padding                  10             \
                window_gap                     10

# Allowlist approach to managed apps (manage = off for everything except these apps)
yabai -m rule --add app!="^(Code|Fantastical|Google Chrome|KakaoTalk|kitty|LINE|Messages|Notes|Notion|Signal|Sonos|Spotify|Sublime Text|Superhuman|Todoist|WhatsApp|Xcode)$" manage=off

yabai -m space 1 --label org
yabai -m rule --add app="^Fantastical$" space=org
yabai -m rule --add app="^Superhuman$" space=org
yabai -m rule --add app="^Todoist$" space=org


borders active_color="gradient(top_left=0xffff9e64,bottom_right=0xffbb9af7)" inactive_color="gradient(top_left=0x40ff9e64,bottom_right=0x40bb9af7)" width=4 2>/dev/null 1>&2 &

echo "yabai configuration loaded"
