#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar                   all:24:0       \
                mouse_follows_focus            on             \
                focus_follows_mouse            autofocus      \
                window_zoom_persist            off            \
                window_placement               second_child   \
                window_shadow                  on             \
                window_opacity                 on             \
                window_opacity_duration        0.0            \
                active_window_opacity          1.0            \
                normal_window_opacity          0.90           \
                window_animation_duration      0.0            \
                window_animation_frame_rate    120            \
                window_animation_easing        ease_out_quint \
                insert_feedback_color          0xff9dd274     \
                split_ratio                    0.50           \
                split_type                     auto           \
                auto_balance                   off            \
                layout                         bsp            \
                mouse_modifier                 fn             \
                mouse_action1                  move           \
                mouse_action2                  resize         \
                mouse_drop_action              swap           \
                top_padding                    4              \
                bottom_padding                 4              \
                left_padding                   4              \
                right_padding                  4              \
                window_gap                     6

# Rules: Management
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom\.us|Photo Booth|Archive Utility|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="DataGrip" app="^DataGrip$" title="(Data Sources and Drivers|Settings)" manage=off
yabai -m rule --add label="LINE" app="^LINE$" title!="^LINE$" manage=off
yabai -m rule --add label="KakaoTalk" app="^KakaoTalk$" title!="^KakaoTalk$" manage=off
yabai -m rule --add app="^Neovide$" manage=on

yabai -m rule --add app="^Finder$" title!="(Co(py|nnect)|Move|Info|Pref)" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Sublime Text$" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^Finder$" title="" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^Home$" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^1Password$" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^zoom\.us$" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^Preview$" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="^Home Assistant$" manage=off grid=6:4:1:1:2:4

# Rules: Layout
yabai -m rule --add app="^Google Chrome$" opacity=1.0
yabai -m rule --add app="^Firefox$" opacity=1.0
yabai -m rule --add app="^zoom.us$" opacity=1.0


borders active_color="gradient(top_left=0xffff9e64,bottom_right=0xffbb9af7)" inactive_color="gradient(top_left=0x40ff9e64,bottom_right=0x40bb9af7)" width=6 2>/dev/null 1>&2 &

echo "yabai configuration loaded"
