#!/usr/bin/env zsh

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults

sketchybar --bar height=48 \
	color="$TRANSPARENT" \
	padding_right=8 \
	padding_left=8 \
	y_offset=0 \
	margin=0 \
	notch_width=200

sketchybar --default updates=when_shown \
	padding_right=2 \
	padding_left=2 \
	icon.font="$FONT:Regular:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Regular:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.height=32 \
	background.corner_radius="$CORNER_RADIUS" \
	background.border_width="$BORDER_WIDTH" \
	background.color="$BAR_COLOR" \
	popup.background.border_width=2 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
# temp disabling as noisy and too big
# source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/media_ctrl.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."

##### FOR LUA
# #!/usr/bin/env lua

# require("init")