#!/usr/bin/env bash

. $HOME/.xenv.sh

if [[ -f "/usr/libexec/polkit-gnome-authentication-agent-1" ]]; then
    exec /usr/libexec/polkit-gnome-authentication-agent-1
elif command -v lxqt-policykit-agent > /dev/null 2>&1; then
    exec lxqt-policykit-agent
elif command -v lxsession > /dev/null 2>&1; then
    exec lxsession
else
    exit 1
fi

