#! /bin/sh

# detect desk setup or just laptop
if [[ $(xrandr --query | grep " connected primary" | cut -d" " -f1) == "DP-3" ]]; then
    bspc monitor DP-3 -d 1 2 3 4 5 6 7 8
    bspc monitor DP-4 -d 9
    bspc wm --reorder-monitors DP-3 DP-4
elif [[ $(xrandr --query | grep " connected primary" | cut -d" " -f1) == "DP-4" ]]; then
    bspc monitor DP-3 -d 9 
    bspc monitor DP-4 -d 1 2 3 4 5 6 7 8
    bspc wm --reorder-monitors DP-4 DP-3
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width            2
bspc config window_gap              20 
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config split_ratio             0.5 
bspc config borderless_monocle      true
bspc config gapless_monocle         true

sleep 3
# sv force-shutdown $HOME/.runit/runsvdir/*

