#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# detect desk setup or just laptop
if [[ $(bspc query -M --names | grep 4) == "DP4" ]]; then
    bspc monitor DP3 -d 9
    bspc monitor DP4 -d 1 2 3 4 5 6 7 8
    bspc wm --reorder-monitors DP4 DP3
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width            2
bspc config window_gap              12
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config split_ratio             0.5 
bspc config borderless_monocle      true
bspc config gapless_monocle         true

