#!/usr/bin/env bash

export MONITOR=eDP-1
connected=$(xrandr --listactivemonitors | grep "\s$MONITOR")

sleep 3

if command -v polybar > /dev/null 2>&1 && [[ $connected != "" ]] && sv check "$HOME/.runit/runsvdir/pipewire-pulse"; then
    exec polybar -q main -c "$HOME/.config/polybar/config.ini"
else
    exit 1
fi

